#!/bin/bash
NOW=$(date "+%Y_%m_%d_%H-%M")

if [ "$1" = "db" ]; then # If node is db ensure if user wants to destroy 
	vagrant destroy $1 && vagrant up $1 > .vagrant/$0_-$1-debug_$NOW.txt
else
	vagrant destroy --force $1 && vagrant up $1 > .vagrant/$0_-$1-debug_$NOW.txt
fi

